- name: Realizar Backup dos Dados Críticos
  become: true
  hosts: all
  tasks:
    - name: Agendar backup
      cron:
        name: "Agendar Backup"
        minute: "1"
        job: "rsync -avz /var/www/html/wess.com/src/docker/redis /var/backups/"
    - name: "Habilitar cron"
      shell:  systemctl enable cron 
    - name: "Start cron"
      shell:  systemctl start cron 
