- name: Realizar Backup dos Dados Críticos
  become: true
  hosts: all
  tasks:
    - name: Agendar backup
      cron:
        name: "Agendar Backup"
        minute: "1"
        hour: "0"
        job: "rsync -avz /var/www/html/wess.com/src/docker/redis /var/backups/"
