name: 3 - Schedule backup
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        options:
          - production
        description: Name of the target environment.    
      AWS_ACCESS_KEY_ID:
        type: string
        description: aws key access.      
      AWS_SECRET_ACCESS_KEY:
        type: string
        description: aws secret key access.                
      AWS_SESSION_TOKEN:
        type: string
        description: aws session token.
      AWS_REGION:
        type: choice
        options:
          - us-east-1
        description: aws region.   
      BUCKET_NAME:
        type: string
        description: aws bucket name.  

  schedule:
    - cron: '0 0 * * *'  # Executar o backup diariamente às 00:00 UTC
jobs:
  backup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 
        uses: actions/setup-node@v4  
        with:
          node-version: latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID || vars.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY || vars.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ inputs.AWS_SESSION_TOKEN || vars.AWS_SESSION_TOKEN }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Install SSH key
        run: mkdir ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - run: echo "${{ vars.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      #- name: Move backup folder to S3
       # run: |
        #  aws s3 cp /path/to/var/backup s3://${{ inputs.BUCKET_NAME }}/backup --recursive
