name: Terraform CI
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      AWS_ACCESS_KEY_ID:
        type: string
        required: true
        description: aws key access.      
      AWS_SECRET_ACCESS_KEY:
        type: string
        required: true
        description: aws secret key access.                
      AWS_SESSION_TOKEN:
          type: string
          required: true
          description: aws session token.                  
jobs:
  terraform:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      TF_LOG: INFO
      TF_INPUT: false
      TF_ACTIONS_WORKING_DIR: "/terraform"
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: echo env
      run: echo GITHUB_ENV
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{ vars.TF_ACTIONS_WORKING_DIR }}
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN:  ${{ inputs.AWS_SESSION_TOKEN }}
        
