name: Terraform CI
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.    
      AWS_ACCESS_KEY_ID:
        type: string
        required: true
        description: aws key access.      
      AWS_SECRET_ACCESS_KEY:
        type: string
        required: true
        description: aws secret key access.                
      AWS_SESSION_TOKEN:
          type: string
          required: true
          description: aws session token.                  
jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      TF_LOG: INFO
      TF_INPUT: false
      TF_ACTION_WORKING_DIR: './terraform'
    environment: ${{ inputs.environment }}
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: ${{ vars.TF_ACTION_WORKING_DIR }}
        AWS_ACCESS_KEY_ID:  ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN:  ${{ inputs.AWS_SESSION_TOKEN }}
